version: '2'
services:
  twoflowerui:
    env_file:
      - ui/global.env
    image: twoflowerui 
    ports:
     - "80:80"
    depends_on:
     - twoflowerapi 
  twoflowerapi:
    env_file:
      - api/global.env
    image: twoflowerapi 
    ports:
     - "8000:80"
    depends_on:
     - redis
     - postgres 
  postgres:
    image: postgres
    volumes:
     - ./storage/postgres:/var/lib/postgresql/data/
#    ports:
#     - "5432:5432"
  redis:
    env_file:
      - redis/global.env
    image: twoflowerredis 
    volumes:
    - ./storage/redis:/data
    ports:
     - "8888:80"
