version: '2'
services:
  twoflowerui:
    env_file:
      - ui/global.env
    image: twoflowerui 
    ports:
     - "5001:5001"
    depends_on:
     - twoflowerapi 
  twoflowerapi:
    env_file:
      - api/global.env
    image: twoflowerapi 
    ports:
     - "5000:5000"
    depends_on:
     - redis
  redis:
    image: bitnami/redis:latest
    volumes:
    - ./db:/bitnami/redis
